### ISSUE TITLE
Addの実装方法について

### ISSUE THREAD

**Issue by yamakii** [kuwana-kb/ddd-in-rust#17]
こちらの[ブログ](https://caddi.tech/archives/1373#Value_Object)を参考にさせていただきました。
DDDのvalue objectのrustでのサンプルがとてもわかりやすかったです。

私もrustでDDDを勉強中でして、
MoneyでのAddの実装方法について教えてください。
https://github.com/kuwana-kb/ddd-in-rust/blob/b936faa50f486318d481ac7171bcbd4ef0efeada/chapter02_value_object/src/a5_vo_with_phantom.rs#L52

ここの後で仮に
```
    let jpy_3 = Money::<JPY>::new(Decimal::new(3, 0));
    let result1 = jpy_1 + jpy_3;
```
のような形でjpy_1を再度呼び出すとCopyがないので、コンパイルエラーになってしまうのかなと思いました。

ここのところは単純にCopyを追加すると考えてもよいものでしょうか？

**Comment by kuwana-kb** [comment]
@yamakii 
ブログをご覧いただきありがとうございます。
ご参考になったようで嬉しいです。

ご質問頂いた件ですが、
> 再度呼び出すとCopyがないので、コンパイルエラーになってしまうのかなと思いました。

こちら、ご指摘のとおりだと思います。
`Add` trait の `add()` メソッドのシグネチャが `self` を要求するため、再度呼び出したい場合は `Clone` か `Copy` の利用は避けられないと思います。

test に記述された内容は、`jpy_1`  `jpy_2`をそれぞれ1度しかつかわないシンプルなユースケースですが、
現実のアプリケーションでは同じ値を複数回利用するケースもあると思います。
今回の場合は、ご指摘の通り `Money` 型に対して`Copy` trait を実装するのが良いと思います。

一応、`Copy` trait を実装せずに52行目で以下のように `clone()` を呼ぶことでもコンパイルエラーを回避することはできますが、
```
let result = jpy_1.clone() + jpy_2; 
```
`Copy` trait を実装できる場合はこれを実装したほうが冗長な`.clone()`の記述を省けてシンプルだと思います。

**Comment by yamakii** [comment]
@kuwana-kb 
確認いただきありがとうございます。
疑問が解決して助かりましたmm
